In [28]:
import numpy as np

arthmetic operation


In [29]:
a1=np.array([1,23,3,4,5,])
a2=np.array([12,323,42,424,23])
a1

array([ 1, 23,  3,  4,  5])

In [30]:
a1+a2

array([ 13, 346,  45, 428,  28])

In [31]:
a1-a2

array([ -11, -300,  -39, -420,  -18])

In [32]:
a1**a2

array([                   1, -3150044729794230905, -1261475310744950487,
                          0,    11920928955078125])

In [33]:
a1*a2

array([  12, 7429,  126, 1696,  115])

In [34]:
a1/a2

array([0.08333333, 0.07120743, 0.07142857, 0.00943396, 0.2173913 ])

In [35]:
a1%a2

array([ 1, 23,  3,  4,  5])

In [36]:
a1//a2

array([0, 0, 0, 0, 0])

broadcast

In [39]:
l=[2,1,212,2]
arr=np.array(l)

In [40]:
arr+10

array([ 12,  11, 222,  12])

In [43]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [44]:
arr+41

array([[42, 43, 44, 45, 46],
       [47, 48, 49, 50, 51],
       [52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61],
       [62, 63, 64, 65, 66],
       [67, 68, 69, 70, 71]])

In [45]:
arr*12

array([[ 12,  24,  36,  48,  60],
       [ 72,  84,  96, 108, 120],
       [132, 144, 156, 168, 180],
       [192, 204, 216, 228, 240],
       [252, 264, 276, 288, 300],
       [312, 324, 336, 348, 360]])

deep and shallow copy


In [49]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])