In [2]:
import numpy as np

arthmetic operation


In [3]:
a1=np.array([1,23,3,4,5,])
a2=np.array([12,323,42,424,23])
a1

array([ 1, 23,  3,  4,  5])

In [4]:
a1+a2

array([ 13, 346,  45, 428,  28])

In [5]:
a1-a2

array([ -11, -300,  -39, -420,  -18])

In [6]:
a1**a2

array([                   1, -3150044729794230905, -1261475310744950487,
                          0,    11920928955078125])

In [7]:
a1*a2

array([  12, 7429,  126, 1696,  115])

In [8]:
a1/a2

array([0.08333333, 0.07120743, 0.07142857, 0.00943396, 0.2173913 ])

In [9]:
a1%a2

array([ 1, 23,  3,  4,  5])

In [10]:
a1//a2

array([0, 0, 0, 0, 0])

broadcast

In [11]:
l=[2,1,212,2]
arr=np.array(l)

In [12]:
arr+10

array([ 12,  11, 222,  12])

In [13]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [14]:
arr+41

array([[42, 43, 44, 45, 46],
       [47, 48, 49, 50, 51],
       [52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61],
       [62, 63, 64, 65, 66],
       [67, 68, 69, 70, 71]])

In [15]:
arr*12

array([[ 12,  24,  36,  48,  60],
       [ 72,  84,  96, 108, 120],
       [132, 144, 156, 168, 180],
       [192, 204, 216, 228, 240],
       [252, 264, 276, 288, 300],
       [312, 324, 336, 348, 360]])

deep and shallow copy


In [16]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
slice=a[:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [18]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
a[5:6]*10

array([60])

In [20]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
b=a.copy()
b[0]=99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

matrix operation

In [23]:
a=np.array([[1,2,3],[23,32,434],[42,42,42]])
b=np.array([[32,41,1412],[432,32432,443],[4124,232,432]])
a

array([[  1,   2,   3],
       [ 23,  32, 434],
       [ 42,  42,  42]])

In [24]:
np.dot(a,b)

array([[  13268,   65601,    3594],
       [1804376, 1139455,  234140],
       [ 192696, 1373610,   96054]])

In [25]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [26]:
A@B

array([[19, 22],
       [43, 50]])

In [27]:
B.T

array([[5, 7],
       [6, 8]])

In [28]:
b.T#htis is a transpose

array([[   32,   432,  4124],
       [   41, 32432,   232],
       [ 1412,   443,   432]])

Advance array manipulatiuon

stacking array

In [29]:
a=np.array([1,23,4,34,3])
b=np.array([1,434,232,32,12])

In [31]:
np.hstack((a,b))

array([  1,  23,   4,  34,   3,   1, 434, 232,  32,  12])

In [32]:
np.vstack((a,b))

array([[  1,  23,   4,  34,   3],
       [  1, 434, 232,  32,  12]])

In [34]:
np.column_stack((a,b))

array([[  1,   1],
       [ 23, 434],
       [  4, 232],
       [ 34,  32],
       [  3,  12]])

splitting array

In [37]:
c=np.arange(16).reshape(4,4)

In [38]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [40]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]