valid sudoku

In [1]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

NameError: name 'np' is not defined

In [ ]:
s.sum()

np.int64(405)

In [ ]:
a=s[0]
a.sum()


np.int64(45)

general question

In [ ]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [ ]:
#Get the shape of the matrix.
data.shape

(5, 3)

#Find the average age of students.

In [ ]:
a=data[:,0]
a

array([18, 19, 17, 18, 20])

In [ ]:
a.mean()


np.float64(18.4)


#Extract Math marks of all students.

In [ ]:
data[:,1]

array([85, 92, 76, 65, 90])

#Find the highest Science mark.

In [ ]:
a=data[:,2]
a.max()


np.int64(95)

In [ ]:
a

array([78, 88, 95, 70, 85])

#Get details of the student who scored more than 90 in Math.

In [ ]:
data[1]

array([19, 92, 88])

#Increase Math marks of all students by 5.

In [ ]:
a=data[:,1]
a*5

array([425, 460, 380, 325, 450])

In [ ]:
a

array([85, 92, 76, 65, 90])

#Find how many students are younger than 19.

In [ ]:
len(data[data[:,0]<19])

NameError: name 'data' is not defined

In [ ]:
a=np.mean(data[:,1:],axis=0)
a

NameError: name 'np' is not defined